### ISSUE TITLE
./iac.tf.sh: line 117: _warning: command not found

### ISSUE THREAD

**Issue by lukemurraynz** [microsoft/symphony#254]
When attempting to use Terraform to destroy (i.e. rename Management Groups), I am getting the below error:

Saved the plan to: terraform.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "terraform.tfplan"
Detect destroy in .tfplan file
./iac.tf.sh: line 117: _warning: command not found

![image](https://github.com/microsoft/symphony/assets/24467442/bd119d04-19cf-4092-9417-ccb404b88ee4)

I added a separate step and can confirm that jq is already the latest version: 
![image](https://github.com/microsoft/symphony/assets/24467442/8c44f6d6-1a70-4d61-9e16-cae23533a0e5)

**Comment by lukemurraynz** [comment]
Within the iac.tf.sh script: ![image](https://github.com/microsoft/symphony/assets/24467442/b1e9d06e-e66f-4fcc-b6ab-5fcef5861ff0)

**Comment by lukemurraynz** [comment]
Adding: 

_warning() {
  echo "WARNING: $1"
}



to the file, resolved the issue.

![image](https://github.com/microsoft/symphony/assets/24467442/a8100712-427e-4296-91bd-920e843e4df7)

![image](https://github.com/microsoft/symphony/assets/24467442/fffe9af1-063b-405a-a4f5-03fc5897d3fc)

**Comment by hattan** [comment]
Closing issue as change has been addressed and merged in.
