### ISSUE TITLE
suggestion: make the ACR optional and refactor the web/db into a sample rather than part of provisioning

### ISSUE THREAD

**Issue by kewalaka** [microsoft/symphony#259]
(this is from a quick skim of the code, so I may have misinterpreted something)

I don't feel ACR should be a pre-requisite for using the framework.  In my opinion, the web & db should be an example wihtin the project that uses the framework.  

The current approach feels like concerns are combined between the framework and the sample app, and a clearer separation would allow for more diverse use cases without requiring additional pre-reqs.

Thoughts?  Have I missed the point? 🤔

**Comment by HadwaAbdelhalem** [comment]
hi @kewalaka , the Azure Container Registry is used to host only the docker images for the sample application that Symphony ships with and is not used by the framework.  If the user decided to change the IaC code to bring their own IaC they can as well remove the ACR instance and the everything shall work as expected. 

For now, we decided to use the shop on web app as a reference implantation.
