### ISSUE TITLE
Difference to Azure Developer CLI

### ISSUE THREAD

**Issue by rajyraman** [microsoft/symphony#260]
I initially wanted to create this under discussions, but since there is no discussions tab in the repo I am creating this as an issue.

Based on my quick look though this looks very much like Azure Developer CLI. What are the differences to azd, and/or advantages of using symphony over azd?

**Comment by HadwaAbdelhalem** [comment]
Hi @rajyraman , Azure Developer CLI is great tool to get you app deployed from local to the cloud in a single command. It also offers a great Varity of templates for different applications, and their IaC code needed. Symphony on the other hand focus on the orchestration, complex deployment, and multi environment aspects of the deployments.

Through Symphony workflows, users can deploy to different environments using separate configurations based on the env type. Symphony offers mature workflows that ensure code quality measure lint linting, validating, and  testing of the IaC modules, along with security scanning as well. 

With Symphony, users get those mature workflows and are able to deploy to multiple environments effortlessly and with no changes to the workflows even when IaC code changes. Feel free to read more on Symphony [Here](https://playbook.microsoft.com/code-with-devsecops/Enterprise-Solutions/infrastructure/provisioning-infrastructure-using-pipelines/)
